import React from 'react'
import PageContainer from './PageContainer';
import { H1 } from '../Elements/headers';
import { THEME } from '../util';

export default function About() {
  return (
    <PageContainer>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ante nunc, ultricies at enim sed, efficitur venenatis neque. Proin tincidunt commodo feugiat. Integer in vulputate diam. Nullam scelerisque imperdiet ante non ullamcorper. Proin molestie maximus est sed ultrices. In facilisis enim sed commodo pharetra. Integer varius arcu vel justo venenatis aliquam ut et augue. Duis pretium felis ligula, et euismod tellus auctor id. In eleifend porttitor lacus, non aliquam turpis scelerisque et.
  
  Cras consequat justo at eleifend euismod. Vestibulum sagittis tincidunt justo sed vulputate. Vivamus viverra faucibus diam non pellentesque. Proin in sodales dui. Etiam porta tempus fringilla. Mauris vel massa id risus congue euismod. Pellentesque faucibus, libero at suscipit volutpat, ligula erat gravida odio, non commodo quam enim vel ante. Pellentesque pellentesque maximus lacinia. Vestibulum congue mauris nec hendrerit facilisis. Ut pellentesque vel enim in elementum.
  
  Nulla maximus, orci malesuada aliquet commodo, felis magna faucibus enim, ut facilisis nisl libero sit amet mauris. Morbi tincidunt semper urna, sit amet dapibus lectus ullamcorper eu. Donec viverra eu tellus eget sollicitudin. Phasellus laoreet sem eros. Aenean ut dui non mi hendrerit posuere sagittis quis mi. Fusce non purus imperdiet, ornare sapien nec, luctus ipsum. Mauris vel elit quis metus dapibus malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse leo est, vestibulum ac maximus id, dictum eu lectus.
  
  Nam porttitor euismod leo, porttitor convallis ante egestas vitae. Duis placerat sit amet sapien vitae scelerisque. Morbi fermentum massa vitae sapien finibus sollicitudin. Pellentesque consequat elit dolor, sit amet volutpat ante facilisis ac. Quisque ultrices id diam in pellentesque. Vivamus eget justo dolor. Praesent nec metus id enim dictum fringilla non sed ligula. Etiam dictum felis sit amet sapien ultricies, non tristique ex eleifend. Sed quis urna nec odio convallis rhoncus vitae a lorem. Nullam semper a nibh id tincidunt.
  
  Nunc tempor ipsum sit amet ante finibus, non feugiat urna consectetur. Donec scelerisque mauris at ante finibus dignissim. Aenean id turpis ut tortor vulputate vulputate. Fusce vel luctus sapien. Praesent a mi vitae quam sagittis accumsan. Vivamus venenatis facilisis eros ac molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate velit id augue tempus, sit amet consequat metus congue. Cras venenatis mi at ligula lacinia semper. Nam luctus quam non luctus dapibus. Duis sed massa sem.
      </p>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ante nunc, ultricies at enim sed, efficitur venenatis neque. Proin tincidunt commodo feugiat. Integer in vulputate diam. Nullam scelerisque imperdiet ante non ullamcorper. Proin molestie maximus est sed ultrices. In facilisis enim sed commodo pharetra. Integer varius arcu vel justo venenatis aliquam ut et augue. Duis pretium felis ligula, et euismod tellus auctor id. In eleifend porttitor lacus, non aliquam turpis scelerisque et.
  
  Cras consequat justo at eleifend euismod. Vestibulum sagittis tincidunt justo sed vulputate. Vivamus viverra faucibus diam non pellentesque. Proin in sodales dui. Etiam porta tempus fringilla. Mauris vel massa id risus congue euismod. Pellentesque faucibus, libero at suscipit volutpat, ligula erat gravida odio, non commodo quam enim vel ante. Pellentesque pellentesque maximus lacinia. Vestibulum congue mauris nec hendrerit facilisis. Ut pellentesque vel enim in elementum.
  
  Nulla maximus, orci malesuada aliquet commodo, felis magna faucibus enim, ut facilisis nisl libero sit amet mauris. Morbi tincidunt semper urna, sit amet dapibus lectus ullamcorper eu. Donec viverra eu tellus eget sollicitudin. Phasellus laoreet sem eros. Aenean ut dui non mi hendrerit posuere sagittis quis mi. Fusce non purus imperdiet, ornare sapien nec, luctus ipsum. Mauris vel elit quis metus dapibus malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse leo est, vestibulum ac maximus id, dictum eu lectus.
  
  Nam porttitor euismod leo, porttitor convallis ante egestas vitae. Duis placerat sit amet sapien vitae scelerisque. Morbi fermentum massa vitae sapien finibus sollicitudin. Pellentesque consequat elit dolor, sit amet volutpat ante facilisis ac. Quisque ultrices id diam in pellentesque. Vivamus eget justo dolor. Praesent nec metus id enim dictum fringilla non sed ligula. Etiam dictum felis sit amet sapien ultricies, non tristique ex eleifend. Sed quis urna nec odio convallis rhoncus vitae a lorem. Nullam semper a nibh id tincidunt.
  
  Nunc tempor ipsum sit amet ante finibus, non feugiat urna consectetur. Donec scelerisque mauris at ante finibus dignissim. Aenean id turpis ut tortor vulputate vulputate. Fusce vel luctus sapien. Praesent a mi vitae quam sagittis accumsan. Vivamus venenatis facilisis eros ac molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate velit id augue tempus, sit amet consequat metus congue. Cras venenatis mi at ligula lacinia semper. Nam luctus quam non luctus dapibus. Duis sed massa sem.
      </p>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ante nunc, ultricies at enim sed, efficitur venenatis neque. Proin tincidunt commodo feugiat. Integer in vulputate diam. Nullam scelerisque imperdiet ante non ullamcorper. Proin molestie maximus est sed ultrices. In facilisis enim sed commodo pharetra. Integer varius arcu vel justo venenatis aliquam ut et augue. Duis pretium felis ligula, et euismod tellus auctor id. In eleifend porttitor lacus, non aliquam turpis scelerisque et.
  
  Cras consequat justo at eleifend euismod. Vestibulum sagittis tincidunt justo sed vulputate. Vivamus viverra faucibus diam non pellentesque. Proin in sodales dui. Etiam porta tempus fringilla. Mauris vel massa id risus congue euismod. Pellentesque faucibus, libero at suscipit volutpat, ligula erat gravida odio, non commodo quam enim vel ante. Pellentesque pellentesque maximus lacinia. Vestibulum congue mauris nec hendrerit facilisis. Ut pellentesque vel enim in elementum.
  
  Nulla maximus, orci malesuada aliquet commodo, felis magna faucibus enim, ut facilisis nisl libero sit amet mauris. Morbi tincidunt semper urna, sit amet dapibus lectus ullamcorper eu. Donec viverra eu tellus eget sollicitudin. Phasellus laoreet sem eros. Aenean ut dui non mi hendrerit posuere sagittis quis mi. Fusce non purus imperdiet, ornare sapien nec, luctus ipsum. Mauris vel elit quis metus dapibus malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse leo est, vestibulum ac maximus id, dictum eu lectus.
  
  Nam porttitor euismod leo, porttitor convallis ante egestas vitae. Duis placerat sit amet sapien vitae scelerisque. Morbi fermentum massa vitae sapien finibus sollicitudin. Pellentesque consequat elit dolor, sit amet volutpat ante facilisis ac. Quisque ultrices id diam in pellentesque. Vivamus eget justo dolor. Praesent nec metus id enim dictum fringilla non sed ligula. Etiam dictum felis sit amet sapien ultricies, non tristique ex eleifend. Sed quis urna nec odio convallis rhoncus vitae a lorem. Nullam semper a nibh id tincidunt.
  
  Nunc tempor ipsum sit amet ante finibus, non feugiat urna consectetur. Donec scelerisque mauris at ante finibus dignissim. Aenean id turpis ut tortor vulputate vulputate. Fusce vel luctus sapien. Praesent a mi vitae quam sagittis accumsan. Vivamus venenatis facilisis eros ac molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate velit id augue tempus, sit amet consequat metus congue. Cras venenatis mi at ligula lacinia semper. Nam luctus quam non luctus dapibus. Duis sed massa sem.
      </p>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ante nunc, ultricies at enim sed, efficitur venenatis neque. Proin tincidunt commodo feugiat. Integer in vulputate diam. Nullam scelerisque imperdiet ante non ullamcorper. Proin molestie maximus est sed ultrices. In facilisis enim sed commodo pharetra. Integer varius arcu vel justo venenatis aliquam ut et augue. Duis pretium felis ligula, et euismod tellus auctor id. In eleifend porttitor lacus, non aliquam turpis scelerisque et.
  
  Cras consequat justo at eleifend euismod. Vestibulum sagittis tincidunt justo sed vulputate. Vivamus viverra faucibus diam non pellentesque. Proin in sodales dui. Etiam porta tempus fringilla. Mauris vel massa id risus congue euismod. Pellentesque faucibus, libero at suscipit volutpat, ligula erat gravida odio, non commodo quam enim vel ante. Pellentesque pellentesque maximus lacinia. Vestibulum congue mauris nec hendrerit facilisis. Ut pellentesque vel enim in elementum.
  
  Nulla maximus, orci malesuada aliquet commodo, felis magna faucibus enim, ut facilisis nisl libero sit amet mauris. Morbi tincidunt semper urna, sit amet dapibus lectus ullamcorper eu. Donec viverra eu tellus eget sollicitudin. Phasellus laoreet sem eros. Aenean ut dui non mi hendrerit posuere sagittis quis mi. Fusce non purus imperdiet, ornare sapien nec, luctus ipsum. Mauris vel elit quis metus dapibus malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse leo est, vestibulum ac maximus id, dictum eu lectus.
  
  Nam porttitor euismod leo, porttitor convallis ante egestas vitae. Duis placerat sit amet sapien vitae scelerisque. Morbi fermentum massa vitae sapien finibus sollicitudin. Pellentesque consequat elit dolor, sit amet volutpat ante facilisis ac. Quisque ultrices id diam in pellentesque. Vivamus eget justo dolor. Praesent nec metus id enim dictum fringilla non sed ligula. Etiam dictum felis sit amet sapien ultricies, non tristique ex eleifend. Sed quis urna nec odio convallis rhoncus vitae a lorem. Nullam semper a nibh id tincidunt.
  
  Nunc tempor ipsum sit amet ante finibus, non feugiat urna consectetur. Donec scelerisque mauris at ante finibus dignissim. Aenean id turpis ut tortor vulputate vulputate. Fusce vel luctus sapien. Praesent a mi vitae quam sagittis accumsan. Vivamus venenatis facilisis eros ac molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate velit id augue tempus, sit amet consequat metus congue. Cras venenatis mi at ligula lacinia semper. Nam luctus quam non luctus dapibus. Duis sed massa sem.
      </p>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ante nunc, ultricies at enim sed, efficitur venenatis neque. Proin tincidunt commodo feugiat. Integer in vulputate diam. Nullam scelerisque imperdiet ante non ullamcorper. Proin molestie maximus est sed ultrices. In facilisis enim sed commodo pharetra. Integer varius arcu vel justo venenatis aliquam ut et augue. Duis pretium felis ligula, et euismod tellus auctor id. In eleifend porttitor lacus, non aliquam turpis scelerisque et.

Cras consequat justo at eleifend euismod. Vestibulum sagittis tincidunt justo sed vulputate. Vivamus viverra faucibus diam non pellentesque. Proin in sodales dui. Etiam porta tempus fringilla. Mauris vel massa id risus congue euismod. Pellentesque faucibus, libero at suscipit volutpat, ligula erat gravida odio, non commodo quam enim vel ante. Pellentesque pellentesque maximus lacinia. Vestibulum congue mauris nec hendrerit facilisis. Ut pellentesque vel enim in elementum.

Nulla maximus, orci malesuada aliquet commodo, felis magna faucibus enim, ut facilisis nisl libero sit amet mauris. Morbi tincidunt semper urna, sit amet dapibus lectus ullamcorper eu. Donec viverra eu tellus eget sollicitudin. Phasellus laoreet sem eros. Aenean ut dui non mi hendrerit posuere sagittis quis mi. Fusce non purus imperdiet, ornare sapien nec, luctus ipsum. Mauris vel elit quis metus dapibus malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse leo est, vestibulum ac maximus id, dictum eu lectus.

Nam porttitor euismod leo, porttitor convallis ante egestas vitae. Duis placerat sit amet sapien vitae scelerisque. Morbi fermentum massa vitae sapien finibus sollicitudin. Pellentesque consequat elit dolor, sit amet volutpat ante facilisis ac. Quisque ultrices id diam in pellentesque. Vivamus eget justo dolor. Praesent nec metus id enim dictum fringilla non sed ligula. Etiam dictum felis sit amet sapien ultricies, non tristique ex eleifend. Sed quis urna nec odio convallis rhoncus vitae a lorem. Nullam semper a nibh id tincidunt.

Nunc tempor ipsum sit amet ante finibus, non feugiat urna consectetur. Donec scelerisque mauris at ante finibus dignissim. Aenean id turpis ut tortor vulputate vulputate. Fusce vel luctus sapien. Praesent a mi vitae quam sagittis accumsan. Vivamus venenatis facilisis eros ac molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate velit id augue tempus, sit amet consequat metus congue. Cras venenatis mi at ligula lacinia semper. Nam luctus quam non luctus dapibus. Duis sed massa sem.
      </p>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ante nunc, ultricies at enim sed, efficitur venenatis neque. Proin tincidunt commodo feugiat. Integer in vulputate diam. Nullam scelerisque imperdiet ante non ullamcorper. Proin molestie maximus est sed ultrices. In facilisis enim sed commodo pharetra. Integer varius arcu vel justo venenatis aliquam ut et augue. Duis pretium felis ligula, et euismod tellus auctor id. In eleifend porttitor lacus, non aliquam turpis scelerisque et.

Cras consequat justo at eleifend euismod. Vestibulum sagittis tincidunt justo sed vulputate. Vivamus viverra faucibus diam non pellentesque. Proin in sodales dui. Etiam porta tempus fringilla. Mauris vel massa id risus congue euismod. Pellentesque faucibus, libero at suscipit volutpat, ligula erat gravida odio, non commodo quam enim vel ante. Pellentesque pellentesque maximus lacinia. Vestibulum congue mauris nec hendrerit facilisis. Ut pellentesque vel enim in elementum.

Nulla maximus, orci malesuada aliquet commodo, felis magna faucibus enim, ut facilisis nisl libero sit amet mauris. Morbi tincidunt semper urna, sit amet dapibus lectus ullamcorper eu. Donec viverra eu tellus eget sollicitudin. Phasellus laoreet sem eros. Aenean ut dui non mi hendrerit posuere sagittis quis mi. Fusce non purus imperdiet, ornare sapien nec, luctus ipsum. Mauris vel elit quis metus dapibus malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse leo est, vestibulum ac maximus id, dictum eu lectus.

Nam porttitor euismod leo, porttitor convallis ante egestas vitae. Duis placerat sit amet sapien vitae scelerisque. Morbi fermentum massa vitae sapien finibus sollicitudin. Pellentesque consequat elit dolor, sit amet volutpat ante facilisis ac. Quisque ultrices id diam in pellentesque. Vivamus eget justo dolor. Praesent nec metus id enim dictum fringilla non sed ligula. Etiam dictum felis sit amet sapien ultricies, non tristique ex eleifend. Sed quis urna nec odio convallis rhoncus vitae a lorem. Nullam semper a nibh id tincidunt.

Nunc tempor ipsum sit amet ante finibus, non feugiat urna consectetur. Donec scelerisque mauris at ante finibus dignissim. Aenean id turpis ut tortor vulputate vulputate. Fusce vel luctus sapien. Praesent a mi vitae quam sagittis accumsan. Vivamus venenatis facilisis eros ac molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate velit id augue tempus, sit amet consequat metus congue. Cras venenatis mi at ligula lacinia semper. Nam luctus quam non luctus dapibus. Duis sed massa sem.
      </p>
      <H1 color={THEME.about.color}>About</H1>
    </PageContainer >
  )
}
